#!/bin/bash

usage () {
    echo "usage: $0 file"
    echo "Open file in started emacs largest window."
}

if [ $# -eq 1 ]; then
   filepath=$(realpath "$1")
   emacsclient -e "(find-file-in-largest-window \"${filepath}\")"
else
    usage
    exit 1
fi
